#pragma once
#define UWORLD 0x12ED8E38 //UWORLD/GWORLD
#define GAME_INSTANCE 0x1f0 //GAMEINSTANCE
#define LOCAL_PLAYERS 0x38 //LOCALPLAYERS
#define PLAYER_CONTROLLER 0x30 //PLAYERCONTROLLER
#define LOCAL_PAWN 0x350 //LOCALPAWN //AACTOR
#define PAWN_PRIVATE 0x320 //PAWNPRIVATE /ACCTOR I THINK
#define ROOT_COMPONENT 0x1B0 //ROOTC /ROOTCOMPONENT
#define RELATIVE_LOCATION 0x120 //RELATIVELOCATION
#define PLAYER_STATE 0x2B0 //PLAYERSTATE //DONTREMEBER WHERE IT IS IN SDK
#define TEAM_INDEX 0x1239 //DONTREMEBER WHERE IT IS IN SDK
#define GAME_STATE 0x178 //GAMESTATE
#define PLAYER_ARRAY 0x2C0 //PLAYERARRAY
#define MESH 0x328 //DONTREMEBER WHERE IT IS IN SDK
#define COMPONENT_TO_WORLD 0x1c0 //COMPONENTTOWORLD //CTOWORLD ///DONTREMEBER WHERE IT IS IN SDK
#define BONE_ARRAY 0x580 //DONTREMEBER WHERE IT IS IN SDK
#define BONE_ARRAY_CACHE 0x590 //DONTREMEBER WHERE IT IS IN SDK
#define LAST_SUBMIT_TIME 0x2EC //DONTREMEBER WHERE IT IS IN SDK
#define LAST_SUBMIT_TIME_ON_SCREEN 0x2F0 //DONTREMEBER WHERE IT IS IN SDK

//ALL OFFSETS HERE!
//THATS ALL THE OFFSETS YOU NEED FOR THAT SIMPLE ASS BASE
//IF YOU ADD MORE STUFF KEEP IN MIND THAT YOU MIGHT NEED MORE OFFSETS !
//ALL OFFSETS UPDATED FOR ++Fortnite+Release-32.11-CL-38202817-Windows
//LAST UPDATED WAS 24/11/2024 (TODAY)